### ISSUE TITLE
Home page Header image change

### ISSUE THREAD

**Issue by greenervigil** [GreenField-Org/LBX-theme#28]
##AC 
- use the current sites image for the header image on the home page.

**Comment by greenervigil** [comment]
There is a weird line breaking up the image on smaller screens: 



![Image](https://user-images.githubusercontent.com/16470877/207896072-09600524-681d-4243-9e9e-dadc1fbb024e.png)

**Comment by hannamlittlefield** [comment]
Updated to remove white line.

**Comment by hannamlittlefield** [comment]
Per Matt: Image is to bold/high contrast, decrease contrast or add opacity. The thin white line through graphic is not
necessary. “Operational Excellence” font to large and bold, see font notes.
