### ISSUE TITLE
Call to Action

### ISSUE THREAD

**Issue by greenervigil** [GreenField-Org/LBX-theme#43]
Green graphic is too distracting/ bold and edges are pixelated, needs to be removed or replaced. Font too small in paragraph, use size 11 Lato minimum

- Update the pixilated green image. 
- Update font

**Comment by hannamlittlefield** [comment]
See Home Page for review - will change to all pages if review OK

**Comment by greenervigil** [comment]
All I see is the blue container, I do not see any copy.

**Comment by greenervigil** [comment]
I made the update on the library.  There were some issues with the right container not fitting in the outer container when in tablet and mobile.  Added the section to all the other pages.
