### ISSUE TITLE
home Header Text

### ISSUE THREAD

**Issue by greenervigil** [GreenField-Org/LBX-theme#45]
## AC 
- Center the Header text on the home page for all views.
- Break the header into two lines try to get 'Life Science Manufacturers' on a separate line

**Comment by greenervigil** [comment]
@hannamlittlefield this appears to now be broken in tablet and mobile.

**Comment by hannamlittlefield** [comment]
@greenervigil I'm not seeing this on my end - can you please screenshot?

**Comment by hannamlittlefield** [comment]
![Image](https://user-images.githubusercontent.com/69218623/209266813-4fe608a5-c89a-479f-84f9-338a696358e3.png)

**Comment by hannamlittlefield** [comment]
![Image](https://user-images.githubusercontent.com/69218623/209266968-40f05556-d982-47cb-95d3-ba458dd8ee15.png)
